apiVersion: v1
kind: ConfigMap
metadata:
  name: servas-app-config
data:
  .env: |
    DB_USERNAME={{ .Values.env.DB_USERNAME }}
    DB_PASSWORD={{ .Values.env.DB_PASSWORD }}
    DB_DATABASE={{ .Values.env.DB_DATABASE }}