apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servas-app-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}