apiVersion: v1
kind: Secret
metadata:
  name: servas-app-secrets
type: Opaque
data:
  DB_USERNAME: {{ .Values.env.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
  DB_DATABASE: {{ .Values.env.DB_DATABASE | b64enc | quote }}