apiVersion: v1
kind: Service
metadata:
  name: servas-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: servas-app
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: servas-db
# spec:
#   type: {{ .Values.dbService.type }}
#   ports:
#     - port: {{ .Values.dbService.port }}
#       targetPort: 3306
#   selector:
#     app: servas-app  