apiVersion: apps/v1
kind: Deployment
metadata:
  name: servas-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: servas-app
  template:
    metadata:
      labels:
        app: servas-app
    spec:
      containers:
        - name: servas
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # securityContext:
          #   runAsUser: 1000 # Reference Kubernetes docs
          #   runAsGroup: 3000 # Configure a Security Context for a Pod or Container
          ports:
            - containerPort: 80
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: servas-app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: servas-app-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: servas-app-secrets
                  key: DB_DATABASE
      volumes: # Add this section
            - name: env-file
              configMap:
                name: servas-app-config
        