replicaCount: 1

image:
  repository: beromir/servas
  pullPolicy: IfNotPresent
  tag: latest

dbImage:
  repository: mariadb
  pullPolicy: IfNotPresent
  tag: 11.7.2

service:
  type: ClusterIP
  port: 80

dbService:
  type: ClusterIP
  port: 3306

env:
  DB_USERNAME: user
  DB_PASSWORD: password
  DB_ROOT_PASSWORD: secret-password
  DB_DATABASE: dbservas

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}